blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://es-ude.github.io/elastic-ai.creator/
    about: Check our documentation before creating an issue
  - name: Discussions
    url: https://github.com/es-ude/elastic-ai.creator/discussions
    about: Please ask and answer questions here
